version: '2.1'

networks:
  # 网络名称
  # 自定义网络名称
  baota:
    # https://docs.docker.com/compose/compose-file/compose-file-v2/#network-configuration-reference 
    driver: bridge

services:
  
  bt:
    image: pch18/baota
    container_name: bt
    volumes: 
      - ${PROJEXT_DIR}:/www/wwwroot
      - ./baota/logs:/www/wwwlogs
    restart: unless-stopped
      # always – 不管退出状态码是什么始终重启容器。当指定always时，docker daemon将无限次数地重启容器。容器也会在daemon启动时尝试重启，不管容器当时的状态如何。
      # no – 容器退出时不要自动重启。这个是默认值。
      # on-failure[:max-retries] – 只在容器以非0状态码退出时重启。可选的，可以退出docker daemon尝试重启容器的次数。
      # unless-stopped - 不管退出状态码是什么始终重启容器，不过当daemon启动时，如果容器之前已经为停止状态，不要尝试启动它。
    ports: 
      - "80:80"
      - "443:443"
      - "8888:8888"
      - "888:888"
      - "3306:3306"
    networks:
      - baota

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports: 
      - "6379:6379"
    networks:
        - baota